apiVersion: v1
kind: Service
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  type: node-api
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    # {{- include "node-api-helm.selectorLabels" . | nindent 4 }}
    app: node-api-test-node-api-helm
